.PHONY: help os9

help:
	@echo "q9edit (OS-9 command: qe)"
	@echo "make os9  - build the current xcc toolchain probe"
	@echo "deploy with: q9edit/tools/deploy-os9.sh DEVELOPMENT.hda"

os9:
	./tools/build-os9.sh
